### ISSUE TITLE
Unhandled exceptions when running GroovyRP

### ISSUE THREAD

**Issue by DeanCSch** [jojo2357/Music-Discord-Presence#1]
When attempting to launch DRP from shortcut, I am faced with this error:

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
at GroovyRP.Program.IsUsingAudio() in Music-Discord-Presence\GroovyRP\Program.cs:line 367
at GroovyRP.Program.Main() in Music-Discord-Presence\GroovyRP\Program.cs:line 123

I have thus far located and linked rich presence with Groove, and have no idea if I need to do anything else.

**Comment by jojo2357** [comment]
which release are you using? I may have forgotten to change the location that the shortcuts point to at some point along the line 😳

**Comment by DeanCSch** [comment]
1.1.1

**Comment by jojo2357** [comment]
Ok, thanks. Ill look into it and rectify it ASAP

**Comment by DeanCSch** [comment]
Thanks, much appreciated!

**Comment by jojo2357** [comment]
Since I can't replicate the issue, I will have to ask you to test the update release package (I added a try-catch since if its erroring there then it should just move on anyway). So if the rich presence doesn't work 🤞 then it gets hard. 

Thanks for showing interest I'm not used to people actually interacting with my work its an exhilarating feeling!

**Comment by jojo2357** [comment]
In case it wasn't clear I changed the zip on 1.1.1 to have the hot fix included. Sorry I just wanna get this resolved quickly. Take your time and close the issue if that fixed it or lmk and I'll look into it more at some point tomorrow.

**Comment by DeanCSch** [comment]
Works perfectly! Thank you so much!
